/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import ticket.booking.entities.Route;
import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.utils.UserServiceUtil;

import java.io.IOException;
import java.util.*;
import org.mindrot.jbcrypt.BCrypt;
public class App {

    public static void main(String[] args) throws IOException {

        System.out.println("Welcome to my Ticket Booking System!");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;

        try{
            userBookingService = new UserBookingService();
        }
        catch (IOException ex){
            System.out.println("There is something wrong!" + ex.getMessage());
            return;
        }

        Train trainSelectedForBooking = null;
        while(option!=7){
        	
        	printMenu();
            
            option = scanner.nextInt();
            scanner.nextLine();
            switch (option){
                case 1:
                	
                	handleSignUp(scanner, userBookingService);
                    
                    break;
                case 2:
                	
                	login(scanner, userBookingService);
                    
                    break;
                case 3:
                    try{
                        userBookingService.fetchBookings();
                    }catch (Exception ex){
                        System.out.println("There is something wrong!");
                    }
                    break;
                case 4:

                	trainSelectedForBooking = searchTrains(scanner, userBookingService);
                   
                    break;

                case 5:
                	
                	bookSeat(scanner, userBookingService, trainSelectedForBooking);
                	
                    break;
                case 6:
                	
                	cancelBooking(scanner, userBookingService);
                   
                    break;
            }
        }
    }
    
    private static void printMenu() {
    	System.out.println("Choose option");
        System.out.println("1. Sign up");
        System.out.println("2. Login");
        System.out.println("3. Fetch Bookings");
        System.out.println("4. Search Trains");
        System.out.println("5. Book a Seat");
        System.out.println("6. Cancel my Booking");
        System.out.println("7. Exit the App");
    }
    
    private static void handleSignUp(Scanner scanner, UserBookingService userBookingService) {
    	String signUpName;
        while(true){
            System.out.println("Enter your username to signup: ");
            signUpName = scanner.nextLine();
            if(signUpName.contains(" ")){
                System.out.println("Username cannot contain spaces!");
            }
            else{
                break;
            }
        }
        System.out.println("Enter your password: ");
        String signUpPass = scanner.nextLine();
        User userToSignup = new User(signUpName, org.mindrot.jbcrypt.BCrypt.hashpw(signUpPass, org.mindrot.jbcrypt.BCrypt.gensalt()), new ArrayList<>(), UUID.randomUUID().toString());
        try{
            boolean userDuplicate = userBookingService.signUp(userToSignup);
            if(userDuplicate){
                System.out.println("Sign up successful!");
            }
            else{
                return;
            }
        }catch (IOException ex){
            System.out.println("Can't SignUp User!");
        }
    }
    
    private static void login(Scanner scanner, UserBookingService userBookingService) {
    	System.out.println("Enter the username to login: ");
    	String username = scanner.nextLine();
    	
        System.out.println("Enter your password: ");
        String password = scanner.nextLine();

        Optional <User> foundUser = userBookingService.getUserByUsername(username);
        if(foundUser.isPresent() && org.mindrot.jbcrypt.BCrypt.checkpw(password, foundUser.get().getHashedPassword())){
            System.out.println("Login successful! Welcome " + username);
            userBookingService.setUser(foundUser.get());
        }
        else{
            System.out.println("Login failed!");
        }
    }
    
    private static void displayAvailableTrains(List<Train> trains) {
        System.out.println("Available Trains:");
        int index = 1;
        for (Train t : trains) {
            t.displayTrainDetails(index); 
            index++;
        }
    }
    
    private static Train searchTrains(Scanner scanner, UserBookingService userBookingService) throws IOException{
    	
        System.out.println("Enter the source station: ");
        String source = scanner.nextLine().toLowerCase(); 
        System.out.println("Enter the destination station: ");
        String destination = scanner.nextLine().toLowerCase(); 

       
        Route searchRoute = new Route(source, destination);
        List<Train> trains = userBookingService.getTrains(searchRoute);

       
        if (trains.isEmpty()) {
            System.out.println("❌ No trains available between " + source + " and " + destination);
            return null;
        }

        displayAvailableTrains(trains);

        System.out.println("Select a train by typing the corresponding number:");

        int selectedIndex;
        while (true) {
            if (scanner.hasNextInt()) {
                selectedIndex = scanner.nextInt();
                scanner.nextLine(); 
                if (selectedIndex > 0 && selectedIndex <= trains.size()) {
                    break;
                } else {
                    System.out.println("❌ Invalid choice! Please select a valid train number.");
                }
            } else {
                System.out.println("❌ Please enter a valid number.");
                scanner.next(); 
            }

            Train selectedTrain = trains.get(selectedIndex - 1); 
            System.out.println("✅ Train Selected: " + selectedTrain.getTrainId());

            System.out.println("Available Seats:");
            selectedTrain.getSeats().displaySeats();
            
            return selectedTrain;
        }
    }

    private static void bookSeat(Scanner scanner, UserBookingService userBookingService, Train trainSelectedForBooking) {
    	 if (trainSelectedForBooking == null) {
             System.out.println("❌ Please select a train first in option 4!");
             return;
         }
         System.out.println("Select a seat out of these seats");

         trainSelectedForBooking.getSeats().displaySeats();

         System.out.println("Select the seat by typing the row and column");

         System.out.println("Enter the row");
         int row = scanner.nextInt();

         System.out.println("Enter the column");
         int col = scanner.nextInt();

         System.out.println("Booking your seat....");

         Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col);

         if(booked.equals(Boolean.TRUE)){
             System.out.println("Booked! Enjoy your journey");
         }else{
             System.out.println("Can't book this seat");
         }
    }
    
    private static void cancelBooking(Scanner scanner, UserBookingService userBookingService) {
    	 System.out.println("Enter the ticket id to cancel the booking");
         String ticketId = scanner.nextLine();
         try {
	         boolean isCancelled = userBookingService.cancelBooking(ticketId);
	
	         if(isCancelled){
	             System.out.println("Booking cancelled successfully!");
	         }
	         else{
	             System.out.println("Booking not found!");
	         }
         }catch (IOException e) {
        	 System.out.println("Error cancelling booking: " + e.getMessage());
         }
    }
}

